name = "arhat-pos-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
[vars]
# Environment variables placeholder
NODE_ENV = "development"

# We will add DB connection strings later
